### ISSUE TITLE
문제 해결 시퀀스 정의

### ISSUE THREAD

**Issue by mtak0235** [couponApiServerEconovation/couponApiServerMtak#4]

**Comment by mtak0235** [comment]
# 문제 해결 시퀀스 정의
#couponServer# #FirstChapter Chapter
## 주요 문제
매번 수동으로 쿠폰을 발행하고,  관리하며,  히스토리를 관리한다.
## 목적
자동으로 쿠폰을 등록하고 관리하며, 사업이슈별로 쿠폰 사용 현황을 리포팅하는 시스템을 만든다.
## 문제 해결을 위한 방법
### 문제 해결 포인트
쿠폰의 등록과 사용을 관리하는 업무 부담이 줄어들고, 쿠폰 사용 내역을 트래킹하여 수익률 계산에 활용할 수 있다. 
### 문제 해결 시퀀스
1. 쿠폰 등록
* 하나의 쿠폰 지정된 단체(VIP)
	* 쿠폰 수량이 정해져 있다. 
	* 쿠폰 사용자 식별 의미없다.
		* 인증 필요 없음.
		* 한 사람이 여러번 사용할 수 있기에 식별 데이터 받아올 필요 없음.
* 하나의 쿠폰 (고객사에 식별가능한)불특정 다수
	* 쿠폰 수량이 정해져 있나?
		* 쿠폰 수량이 정해져 있다.
		* 쿠폰 수량이 정해져 있지 않다.
	* 쿠폰 사용자 식별 의미 있다. 
		* 고객사에 인증 절차 위임했기 때문에 인증이 필요 없음.
		* 식별 데이터 받아와야 함.
* 단체 전용 쿠폰
	* 쿠폰 수량이 정해져 있음
	* 쿠폰 사용자 


2. 쿠폰 사용
3. 
4. 
쿠폰 종류
 	* 하나의 쿠폰 번호 지정된 단체
 	 	화이트 리스트로 단체 규정
 	 	단체 소속 사람만 쓸 수 있게 인증 절차 필요
 	 	-> 고객 입장에서 인증받는 절차가 귀찮을 수 있으니 쿠폰 수량과 인증 페이지만 제공해서 고객사에서 핸들링 할 수 있게 떠넘기자.
 	 	이 부분은 후순위로 배치
 	 * 하나의 쿠폰 번호 모두 사용 가능
 	 	이벤트성 쿠폰 뿌리기
 	 * 개인을 지정하고 쿠폰 발행
 	 	개인 식별 필요
 	 * 발행된 쿠폰을 먼저 등록한 사람이 쿠폰 소유
 	 	일반적인 종이 쿠폰
4. 구독한 사람들에게 정기쿠폰발송 서비스
	* 배치 시스템과 연동 필요
	* 배치 미들웨어 개발팀과 협업해야 하니 후순위
5. 단일 쿠폰을 모아서 특별한 쿠폰 만드는 확장 서비스
	* “이벤트 확장 시스템” 이름으로 phase-2에서 개발(후순위)
6. 다양한 클라이언트를 염두로 두고 인터페이스 만들자. 
	디비 설계시 고려
	서비스 클라이언트 정보가 테이블로 분리되어 있는지 or 다른 테이블에 하드코딩 되어 있는지 확인 필요
7. 쿠폰은 마일리지, 제휴 포인트 처럼 기업에서 제품 가격의 일부를 부담하는 프로세스이기에 쿠폰 발급 프로세스에 금액에 대한 것도 추가해야 한다. 
	우리가 얼마나 많은 돈을 지금 못 벌 것인지 -> 지출 내역		하지만 얼마나 수익을 창출해 내야 했는지 -> 같은 쿠폰을 발행해도 어떤 이슈(마케팅 방법 혹은 운용 방법)로 얼마나 사용했는지 히스토리를 남기자.  
		사람들이 명확하게 계산하고 계획할 수 있게 해야 한다.
## 화이트 리스트: 허가된 것들을 리스트업 해 놓은 것.
## 3
 ## 문제 해결 시퀀스 정의하기

**Comment by mtak0235** [comment]
도연님이랑 같이 작업하자!
구글 독스 vs 노션 
노션이 더 기능이 많으니, 노션을 쓰자

**Comment by capDoYeonLee** [comment]
https://www.notion.so/5aca563ade4b4a1c990a8b75e4e91051

**Comment by mtak0235** [comment]
# 문제 해결 시퀀스 정의

### 주요 문제

---

- 한달에 한번 감사 인사 전하기
- 재방문율 높이기
- 구매욕구 올리기

### 목적

---

쿠폰을 발급해서 고객들에게 리마인드 시킨다.

### 해결 순서 정의

---

1. 쿠폰 종류 정하기
    1. 쿠폰 기간 정하기
    2. 쿠폰 할인률 정하기
    3. 쿠폰 수량 정하기
    4. 인증이 필요한지
        1. 화이트 리스트가 필요한지
            1. 화이트 리스트가 필요하다면, 고객사에게 고객 정보를 요청할 웹사이트 구성
2. 쿠폰 번호 확인 요청이 들어오면 해당 시간, 인터페이스를 로깅
    1. 고객사에 쿠폰 히스토리를 리포팅
    2. 쿠폰 기간이 만료되면 리포팅을 푸쉬한다.
        1. 이메일
3. 고객사가 쿠폰 발급을 신청할 페이지
    1. 구성은 어떻게 생겨야 하나

1. (고객 → 쿠폰 시스템) 쿠폰 등록
    1. 쿠폰을 등록할 자격이 있는 고객인가?
        1. 등록할 자격이 있다.
            1. 쿠폰 등록이 완료 되었다고 고객에게 알린다.
        2. 등록할 자격이 없다.
            1. 고객에게 등록할 수 없다고 알림.
    - 스캘래톤 시퀀스 다이어그램
        
        ![image](https://user-images.githubusercontent.com/48946398/226094470-c5a1bad4-88d1-44ed-b077-0ab78ee99b65.png)
        

2. (사용처 →  쿠폰 시스템) 쿠폰 사용
    1. 쿠폰을 사용할 수 있나?
        1. 사용할 수 있다.
            1. 쿠폰을 사용할 자격이 있나?
                1. 쿠폰을 사용할 자격이 있다.
                    1. 사용처에 쿠폰을 사용할 수 있다고 한다.
                    2. 사용처가 쿠폰이 결제 사용되었다고 알려준다.
                        1. 고객에게 쿠폰이 사용 되었음을 알린다.
                2. 쿠폰을 사용할 자격이 없다.
                    1. 사용처에 쿠폰을 사용할 수 없다고 한다.
        2. 사용할 수 없다.
            1. 사용처에 쿠폰을 사용할 수 없다고 한다.
    - 스캘래톤 시퀀스 다이어그램
        ![image](https://user-images.githubusercontent.com/48946398/226094569-c3390b5d-d612-452d-aede-5b178bc9a979.png)
        
        
3. (고객사 → 쿠폰 시스템)쿠폰 발급
 1. 데이터가 모두 들어왔나?
        1. 모두 들어왔다.
            1. 고객사에 쿠폰 등록이 완료 되었다고 한다.
        2. 모두 들어오지 않았다.
            1. 고객사에 쿠폰을 등록할 수 없다고 한다.
    - 스캘래톤 시퀀스 다이어그램
![image](https://user-images.githubusercontent.com/48946398/226095173-0f33aaac-d093-4531-9bfb-3223ae470932.png)

    
    <데이터>
    
    - 쿠폰 정책 명
    - 쿠폰 할인 구분
        - % 할인
            - 최소 사용 금액
            - 일괄
        - X원 할인
            - 최소 사용 금액
            - 일괄
        - 1 + X 할인
        - 기타
    - 다운로드 할 수 있는 기간
    - 사용할 수 있는 기간
    - 중복 가능 여부
    - 수량 제한 여부
        - 수량 제한 함.
            - 최대 발급 건수
        - 수량 제한 안함.
    - 고객 인증이 필요 여부
        - 쿠폰 푸시 여부
    - 쿠폰 발행 사유
    - 사용 가능 요일
    - 쿠폰 이미지
    - 상품 정보
